require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/*'

Metrics/MethodLength:
  Exclude:
    - 'bin/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/*'

Layout/LineLength:
  Exclude:
    - 'bin/*'
    - 'config/initializers/devise.rb'

Style/FetchEnvVar:
  Exclude:
    - 'bin/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/EagerEvaluationLogMessage:
  Exclude:
    - 'db/seeds.rb'
